kanta_str = input("Suorakulmion kanta: ")
korkeus_str = input("Suorakulmion korkeus: ")
kanta = float(kanta_str)
korkeus = float(korkeus_str)
pintaala = (kanta*korkeus)
print("pintaala " + str(pintaala))
piiri = (2*kanta + korkeus*2)
print("piiri " + str(piiri))